class S3var < ApplicationRecord	
	#konstaan variabel
	AGAMA = ['ISLAM', 'KRISTEN', 'KATOLIK', 'HINDU', 'BUDHA']
	AREA_LAYANAN = [['KOTA','K'],['LUAR KOTA','L']]
	BANK = [['BCA','BCA'],['MANDIRI','MDR'],['BRI','BRI']]

	DIVISI_KERJA = [['FRONT OFFICE','FO'],['BACK-OFFICE','BO'],['OPERASIONAL-LAPANGAN','OP'],['TEKNISI','TE'],['TRANSPORTER','TR']]

	INEX = [['INTERNAL','IN'],['EXTERNAL','EX']]
	
	JENIS_KELAMIN = [['LAKI-LAKI','L'],['PEREMPUAN','P']]
	JENIS_BBM  = ["PREMIUM","PERTAMAX","SOLAR","DEXLITE"]
	JENIS_PULSA = [['TELKOMSEL','TL'],['INDOSAT','IN'],['XL-ASIATA','XL'],['3','3']]
	JENIS_BIAYA_LAIN = [['TIDAK ADA','0'],['TAMBAL BAN DALAM','TB'],['GANTI BAN DALAM','GB'],['SERVICE RANTAI','RAN'],['SERVICE REM','REM'],['PARKIR','PK']]
	
	LEVEL = [['GUEST','1'],['ADMINTRASI','2'],['SUPERVISOR','3'],['OWNER','4'],['CREATOR','5']]

	KEGIATAN =[["PACK-SORTIR","PS"],["UNPAK-SORTIR","US"]]

	MASKAPAI = ["GARUDA","LION","BATIK","WINGS","AIR ASIA","CITILINK","SRIWIJAYA","NAM AIR","SUSI AIR","KALSTAR","EXPRESS AIR","TRANSNUSA","AVIASTAR"]

	NOMINAL_PULSA  = ["100","050","025","020","010","005","001"]

	PEMILIK_KENDARAAN =[['PERUSAHAAN','PT'],['RENTAL EXTERNAL','RE'],['KARYAWAN','KR']]
	POS_BUKU = [["BALANCE SHEET","BS"],["PROFIT AND LOSS","PL"]]
	POS_NILAI = [["DEBET","D"],["KREDIT","K"]]
	POS_JURNAL = [["DETAIL",true],["HEADER",false]]

	ROLE = [['REGISTERED','1'],['ADMIN','2']]
	
	SATUAN = ["Unt","Pcs","Ltr","Rol","Kg","Ons","Gr","Mg","Dus","Rim","Lbr","Zak","Pac","Mtr","Cm","Mm"]

	SHIFT = [['PAGI','1'],['SIANG','2'],['MALAM','3'],['SUBUH','4']]


	STATUS_KARYAWAN = [['KERYAWAN TRAINING','KP-0'],['KARYAWAN TETAP AKTIF','KT-A'],['KARYAWAN TETAP CUTI','KT-C'],['RESIGN','0']]
	STATUS_PERKAWINAN = [['TIDAK KAWIN','TK-0'],['KAWIN 0 TANGGUNGAN','K-T0'],['KAWIN 1 ANAK','K-T1'],['KAWIN 2 ANAK','K-T2'],['KAWIN 3 ANAK','K-T3']] 
	
	STATUS_PULSA = [['REJECT BY PIC-SENSOR','0'],['REJECT BY LIMIT','1'],['TOP-UP SUKSES','2'],['OK-PROSES PENGISIAN','3'],['PERMINTAAN ISI PULSA','5']]	

	TRACKING = [["NORMAL-NON SERIAL NUMBER",2],["SERIAL NUMBER",1],["NON-STOK FISIK",0],["SALDO",4]]
	TRANSAKSI_DP = ['PICKUP','DROP OFF']
end